export const AUTH_SIGN_IN = 'AUTH/SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH/SIGN_OUT';

export const MERCHANT_FETCH_MERCHANTS = 'MERCHANT/FETCH_MERCHANTS';
export const MERCHANT_ADD_MERCHANT = 'MERCHANT/ADD_MERCHANT';

export const UI_IS_DIALOG_OPEN = 'UI/IS_DIALOG_OPEN';