export const AUTH_SIGN_IN = 'AUTH/SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH/SIGN_OUT';

export const MERCHANT_FETCH_MERCHANTS = 'MERCHANT/FETCH_MERCHANTS';
export const MERCHANT_ADD_MERCHANT = 'MERCHANT/ADD_MERCHANT';
export const MERCHANT_EDIT_MERCHANT = 'MERCHANT/EDIT_MERCHANT';
export const MERCHANT_REMOVE_MERCHANT = 'MERCHANT/REMOVE_MERCHANT';
export const MERCHANT_SORT_PREMIUM = 'MERCHANT/SORT_PREMIUM';

export const UI_IS_DIALOG_OPEN = 'UI/IS_DIALOG_OPEN';
export const UI_SET_ACTIVE_TAB = 'UI/SET_ACTIVE_TAB';

export const BID_SORT_BY_TITLE = 'BID/SORT_TITLE';
export const BID_SORT_BY_CREATED_DESC= 'BID/SORT_BY_CREATED_DESC';
export const BID_SORT_BY_CREATED_ASC= 'BID/SORT_BY_CREATED_ASC';